More fixes...
... but still not working:

Configuring hhp-1.0.0.0...
Warning: The flag --disable-executable-profiling is deprecated. Please use
--disable-profiling instead.
Warning: 'hs-source-dirs: exe' directory does not exist.
Warning: 'hs-source-dirs: exe' directory does not exist.
building
Preprocessing test suite 'hlint' for hhp-1.0.0.0..
Building test suite 'hlint' for hhp-1.0.0.0..
building
Setup: Main.hs doesn't exist
builder for '/nix/store/nixwxwhrpj2a5b3p464gz1y5afvcyb68-hhp-1.0.0.0-test-doctests.drv' failed with exit code 1
cannot build derivation '/nix/store/3hrd5v4b2bl4q01rdhzrfzpss6a7lc1w-hhp-1.0.0.0-test-doctests-check.drv': 1 dependencies couldn't be built
error: build of '/nix/store/3hrd5v4b2bl4q01rdhzrfzpss6a7lc1w-hhp-1.0.0.0-test-doctests-check.drv', '/nix/store/b38p9majr0sfdqv76wslhg2zjqcasbsd-hhp-1.0.0.0-test-hlint-check.drv' failed